---
name: MacOS-Codesigner
description: "Apply code signatures and sign MacOS binaries"
author: https://github.com/DoomGerbil
requirements:
  - security
  - altool
  - codesign
  - productsign
  - gon
  - jq
configuration:
  properties:
    input_artifact:
      type: string
    sign_prerequisites:
      type: [ string, array ]
    entitlements:
      type: string
    keychain:
      type: string
    cert_identity:
      type: string
    keychain_pw_secret_name:
      type: string
    keychain_pw_helper_script:
      type: string
    tool_bundle_id:
      type: string
    apple_user_email:
      type: string
  required:
    - input_artifact
    - keychain
    - cert_identity
    - tool_bundle_id
    - apple_user_email
