---
name: MacOS-Codesigner
description: "Apply code signatures and sign MacOS binaries"
author: https://github.com/DoomGerbil
requirements:
  - security
  - gon
  - codesign
  - jq
configuration:
  properties:
    input_artifacts:
      type: [ string, array ]
    sign_prerequisites:
      type: [ string, array ]
    output_artifacts:
      type: [ string, array ]
    entitlements:
      type: string
    keychain:
      type: string
    cert_identity:
      type: string
    keychain_pw_secret_name:
      type: string
    keychain_pw_helper_script:
      type: string
    tool_bundle_id:
      type: string
    apple_user_email:
      type: string
  required:
    - input_artifacts
    - sign_prerequisites
    - output_artifacts
    - keychain
    - cert_identity
    - tool_bundle_id
    - apple_user_email
