---
name: MacOS-Codesigner
description: "Apply code signatures to MacOS binaries"
author: https://github.com/DoomGerbil
# TODO: Discover and list requirements
requirements:
  - imp-vault
  - security
  - codesign
# TODO: Flesh out configuration options
configuration:
  properties:
    input_artifact:
      type: string
    keychain:
      type: string
    keychain_secret:
      type: string
  required:
    - input_artifact
    - keychain
    - keychain_secret
