---
name: MacOS-Codesigner
description: "Apply code signatures to MacOS binaries"
author: https://github.com/DoomGerbil
# TODO: Discover and list requirements
requirements:
  - security
  - codesign
configuration:
  properties:
    input_artifacts:
      type: [ string, array ]
    keychain:
      type: string
    keychain_pw_secret_name:
      type: string
    keychain_pw_helper_script:
      type: string
  required:
    - input_artifacts
    - keychain
