#!/usr/bin/env bash
#
# Actually signs the package.
# 1. Retrieve the unsigned binary from the BK artifact store
# 2. Retrieve the keychain unlock password
# 3. Unlock the keychain
# 4. Sign the binary and validate the signature
# 5. Upload the binary as a BuildKite artifact

set -o errexit -o nounset -o pipefail
[[ -n "${DEBUG-}" ]] && set -x

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/shared.sh
source "${DIR}/../lib/shared.sh"

codesigning_keychain="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN}"
script_root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
default_keychain_pw_helper_script="${script_root_dir}/../helpers/fetch-keychain-pw.sh"

# Fetch the artifact and put it in the target dir
# Params:
#   fetch_target: Name of the BuildKite artifact to fetch
#   dest_dir: Where to download it to.
function fetch_artifact() {
  local fetch_target="${1}"
  local dest_dir="${2}"

  buildkite-agent artifact download "${fetch_target}" "${dest_dir}"

  echo "${dest_dir}/${fetch_target}"
}

# If the unlock secret was not supplied as an env var, call the helper script to fetch it
# Params:
#   helper_script_path: Path to a script to run that returns the keychain PW.
#   rest: Any arguments that need to be passed to the helper script.
function get_keychain_pw() {
  local helper_script_path="${1}"

  if [[ -z "${KEYCHAIN_PW:-}" ]]; then
    KEYCHAIN_PW="$("${helper_script_path}" "${@:2}")"
  fi

  echo "${KEYCHAIN_PW}"
}

# Now unlock the keychain and find the identity to sign with
# Params:
#   keychain_name: The name of an existing, accessible macos Keychain containing one signing certificate.
#   keychain_pw: The password to unlock this keychain.
function unlock_keychain() {
  local keychain_name=${1}
  local keychain_pw=${2}

  security unlock-keychain -p "${keychain_pw}" "${keychain_name}"
}

# Generate gon config for signing+notarization
# Params:
#   prerequisites: variable stub to get list of prerequisites from YAML definition
#   entitlements: path to entitlements file (ignored if empty)
#   artifacts_dir: root path to relevant artifacts
#   config_path: path to write gon config file to
function generate_signing_config() {
  local prerequisites="${1}"
  local entitlements="${2}"
  local artifacts_dir="${3}"
  local config_path="${4}"

  jq -n \
    --arg bundle_id "${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_BUNDLE_ID}" \
    --arg apple_user_email "${BUILDKITE_PLUGIN_MAC_CODESIGN_APPLE_USER_EMAIL}" \
    --arg identity "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" \
    '{
      "source": [],
      "bundle_id": $bundle_id,
      "apple_id": {
        "username": $apple_user_email,
        "password": "@keychain:apple_password",
      },
      "sign": {
        "application_identity": $identity,
      },
    }' >"${config_path}"

  echo "${prerequisites}" | while read -r prereq; do
    # iterate over prerequisites, adding them to the codesign config
    local config
    config="$(jq --arg toSign "${artifacts_dir}/${prereq}" '.source += [$toSign]' "${config_path}")"
    echo "${config}" >"${config_path}"
  done

  if [[ -n "${entitlements}" ]]; then
    # if entitlements specified, add them to config.
    local config
    config="$(jq --arg entitlements "${entitlements}" '.sign.entitlements_file = $entitlements' "${config_path}")"
    echo "${config}" >"${config_path}"
  fi
}

# Generate gon config for notarization
# Params:
#   inputfile: File to notarize
#   config_path: Path to config
function generate_notarization_config() {
  local inputfile="${1}"
  local config_path="${2}"

  jq -n \
    --arg inputfile "${inputfile}" \
    --arg bundle_id "${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_BUNDLE_ID}" \
    --arg apple_user_email "${BUILDKITE_PLUGIN_MAC_CODESIGN_APPLE_USER_EMAIL}" \
    '{
      "notarize": [
        {
        "path": $inputfile,
        "bundle_id": $bundle_id,
        "staple": true,
        }
      ],
      "apple_id": {
        "username": $apple_user_email,
        "password": "@keychain:apple_password",
      },
    }' >"${config_path}"
}

# Handle all the requirements for signing code.
# Params:
#   artifact_dir: Directory where prerequisites are stored.
#   config_path: Path to gon config
#   prerequisites: Files to sign before signing final artifact
#   entitlements: Path to entitlements plist
function sign_code() {
  local artifact_dir="${1}"
  local config_path="${2}"
  local prerequisites="${3}"
  local entitlements="${4}"

  echo "--- Generating signing and notarization config"
  generate_signing_config "${prerequisites}" "${entitlements}" "${artifact_dir}" "${config_path}"

  echo "--- Signing and notarizing"
  gon "${config_path}"
}

# Handle all the requirements for signing packages.
# Params:
#   artifact: pkg file to sign+notarize.
#   signed_artifact: outputpath of signed pkg.
#   config_path: Path to gon config
function sign_pkg() {
  local artifact="${1}"
  local signed_artifact="${2}"
  local config_path="${3}"

  echo "--- Signing PKG file"
  productsign --sign "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" "${artifact}" "${signed_artifact}"

  echo "--- Generating PKG notarization config"
  generate_notarization_config "${signed_artifact}" "${config_path}"

  echo "-- Notarizing PKG"
  gon "${config_path}"
}

# Convenience wrapper to upload our signed artifact to BuildKite
# Params:
#   artifact: Path of a file to upload to BuildKite as an artifact.
function upload_artifact() {
  local artifact="${1}"

  buildkite-agent artifact upload "${artifact}"
}

# Allow the user to override the default keychain pw retrieval helper script.
function find_keychain_pw_helper_script() {
  local script
  script="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT:-${default_keychain_pw_helper_script}}"

  echo "${script}"
}

## Main execution flow

# Set everything up to be able to sign.
echo "--- Getting the password to unlock the keychain"
keychain_pw_helper_script=$(find_keychain_pw_helper_script)
keychain_pw=$(get_keychain_pw "${keychain_pw_helper_script}")

echo "--- Unlocking the keychain"
unlock_keychain "${codesigning_keychain}" "${keychain_pw}"

echo "--- Setting up local directories"
# Download things in a local dir to identify them
artifact_dir_fragment="artifacts"
rm -rf "${artifact_dir_fragment}" && mkdir -p "${artifact_dir_fragment}"

signed_dir_fragment="signed"
rm -rf "${signed_dir_fragment}" && mkdir -p "${signed_dir_fragment}"

## Download requested artifact
artifact="${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}"

if [[ "${artifact}" == *"*"* ]]; then
  echo "inputfile artifacts cannot contain wildcards: '${artifact}'"
  exit 5
fi

echo "--- Downloading requested artifact: ${artifact}"
fetch_artifact "${artifact}" "${artifact_dir_fragment}"

entitlements="${BUILDKITE_PLUGIN_MAC_CODESIGN_ENTITLEMENTS:-}"
if [[ -n "${entitlements}" ]]; then
  echo "--- Downloading entitlements file"
  fetch_artifact "${entitlements}" "${artifact_dir_fragment}"
  entitlements="${artifact_dir_fragment}/${entitlements}"
fi

unsigned_artifact="${artifact_dir_fragment}/${artifact}"
base_artifact="$(basename "${artifact}")"
base_artifact_no_extension="${base_artifact%.*}"
signed_artifact="${signed_dir_fragment}/${base_artifact}"

# Make sure dir structure exists
mkdir -p "$(dirname "${signed_artifact}")"

config_path="config.json"

prerequisites="$(plugin_read_list SIGN_PREREQUISITES)"
if [[ -z "${prerequisites}" ]]; then
  # If no prerequisites are specified, point to the artifact
  prerequisites="${unsigned_artifact}"
fi

echo "--- Preparing to sign artifact: ${unsigned_artifact}"
if [[ "${base_artifact}" == *".pkg" ]]; then
  # PKG files need to be signed with "Developer ID Installer" certs through `productsign`.
  # `gon` only supports "Application" certs, through `codesign`.
  # This steps signs with productsign, and then generates a gon config to notarize it.
  echo "--- Signing PKG artifact"
  sign_pkg "${unsigned_artifact}" "${signed_artifact}" "${config_path}"
else
  if [[ "${base_artifact}" == *".zip" ]]; then
    echo "--- Unzipping downloaded artifact to ${signed_dir_fragment}"
    unzip "${unsigned_artifact}" -d "${signed_dir_fragment}"
  fi

  echo "--- Signing artifact: ${signed_artifact}"
  sign_code "${signed_dir_fragment}" "${config_path}" "${prerequisites}" "${entitlements}"

  if [[ "${base_artifact}" == *".zip" ]]; then
    # move to dir to avoid weird paths in the zip
    pushd "${signed_dir_fragment}"
    echo "--- Zipping signed artifact"
    # -1 for speed
    # -y to preserve symlinks
    # -r for directories
    # -X to remove .DS_STORE etc
    # We are in a clean signed dir, so select all directories (also avoids path mangling)
    zip -1 -y -r -X "${base_artifact}" ./*
    popd
  else
    # Codesign is in place, so move to signed location
    mv "${unsigned_artifact}" "${signed_artifact}"
  fi
fi

echo "--- Uploading output artifacts"
upload_artifact "${signed_artifact}"
upload_artifact "${config_path}"
