#!/usr/bin/env bash
#
# Lock the keychain we used to sign things.

set -o errexit -o nounset -o pipefail
[[ -n "${DEBUG-}" ]] && set -x

# And lock the door behind us
echo "--- Locking signing keychain"

if ! security lock-keychain "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN}"; then
  # TODO: This needs to be able to actually alert us directly if it happens.
  echo "ERROR: Unable to lock codesigning keychain!"
  echo "This can be extremely serious!  Let #eng-velocity know right away!"
  exit 15 # Arbitrary error exit code for this specific condition.
fi
