#!/usr/bin/env bash
#
# Lock the keychain we used to sign things.

[[ -n "${DEBUG-}" ]] && set -x

# Clean up the unsigned artifact
rm -f "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}"

# And lock the door behind us
security lock-keychain "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN}"

if [[ $? -ne 0 ]]; then
  # TODO: This needs to be able to actually alert us directly if it happens.
  echo "ERROR: Unable to lock codesigning keychain!"
  echo "This can be extremely serious!  Let #eng-velocity know right away!"
  exit 5 # Arbitrary error exit code for this specific condition.
fi
